from TikTokApi.tiktok import TikTokApi
from TikTokApi.TrendingComments.get_trending_videos import get_hashtag_videos, trending_videos
from TikTokApi.TrendingComments.get_comments import get_comments, get_comments_for_videos
